Document: 402-status
Title: Debian 402-status Manual
Author: <insert document author here>
Abstract: This manual describes what 402-status is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/402-status/402-status.sgml.gz

Format: postscript
Files: /usr/share/doc/402-status/402-status.ps.gz

Format: text
Files: /usr/share/doc/402-status/402-status.text.gz

Format: HTML
Index: /usr/share/doc/402-status/html/index.html
Files: /usr/share/doc/402-status/html/*.html
